### ISSUE TITLE
Create Lobby Page

### ISSUE THREAD

**Issue by simran-ss-sandhu** [dannyklaris/cloud-group-cw#3]
# Possible Requirements
- Direct users to this page after login
- Show list of players who have joined
- Show difficulty of the game
- Show selected topics

**Comment by dannyklaris** [comment]
i have already added the lobby page in the most recent commit to main, but it is still not perfect. the current flow of the user is now
play as guest -> lobby page -> admin can click next to select type of questions -> admin start the game -> all users play with the same question within the same time -> results -> review -> leaderboard.

i'm thinking of showing the difficulty that is chosen to the user at start.ejs view before they play the game. what do you think?

**Comment by simran-ss-sandhu** [comment]
The user flow seems good and yeah it'd make sense to show the difficulty just before starting the game. If we're letting the admin control when the game starts, maybe we could add a delay (3s) to the start button so they don't accidentally start the game before people get to read the instructions and difficulty.

**Comment by dannyklaris** [comment]
the lobby page is completed at commit 588c644.
